version: '3.8'
services:
  pingvin-share:
    depends_on:
      clamav:
        condition: service_healthy
    image: stonith404/pingvin-share
    restart: unless-stopped
    container_name: Pingvin-Share
    ports:
      - "3535:3000"
    volumes:
      - /home/mrp/docker/pingvin:/opt/app/backend/data
      - /home/mrp/nas/docker-stuff/pingvin:/opt/app/backend/data/uploads
      - /home/mrp/docker/pingvin/images:/opt/app/frontend/public/img
  clamav:
    restart: unless-stopped
    image: clamav/clamav
    container_name: ClamAV
