version: "2.1"
services:
  remmina:
    image: lscr.io/linuxserver/remmina:latest
    container_name: remmina
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/mrp/docker/remmina:/config
    ports:
      - 3002:3000
      - 3001:3001
    restart: unless-stopped
#     networks:
#       - galaxy

# networks:
#   galaxy:  # Updated to correct network name
#     driver: bridge
    