version: '3.8'
services:
  pingvin-share:
    depends_on:
      clamav:
        condition: service_healthy
    image: stonith404/pingvin-share
    restart: unless-stopped
    container_name: Pingvin-Share
    ports:
      - "3535:3000"
    volumes:
      - "/PATH/TO/LOCATION:/opt/app/backend/data"
      - "/PATH/TO/LOCATION:/opt/app/backend/data/uploads"
      - "/PATH/TO/LOCATION:/opt/app/frontend/public/img"
    networks:
      - galaxy
      
###########################################      

  clamav:
    restart: unless-stopped
    image: clamav/clamav
    container_name: clamav
