version: '3.8'
services:
  influxdb:
    image: influxdb
    container_name: Monitor-InfluxDB
    ports:
      - $HOST_PORT:8086
    volumes:
      - $DATA:/var/lib/influxdb2
      - $CONFIG:/etc/influxdb2
    restart: always

#    networks: 
#      - galaxy
#networks:
#  galaxy:
#    driver: bridge
#    # --------------
