version: "3.9"
services:
  it-tools:
    image: corentinth/it-tools:latest
    ports:
      - $HOST_PORT:80
    restart: always
    container_name: $NAME
#    networks:
#      - galaxy
#networks:
#  galaxy:  # Updated to correct network name
#    driver: bridge
